/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <stdbool.h>
#include "utils.h"
/* Header for class com_globerry_project_service_CurveService */

#ifndef _Included_com_globerry_project_service_CurveService
#define _Included_com_globerry_project_service_CurveService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_globerry_project_service_CurveService
 * Method:    calculateCurve
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_globerry_project_service_CurveService_calculateCurve
  (JNIEnv *, jobject, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
